/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApartmentsRouteImport } from './routes/apartments'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApartmentsIdRouteImport } from './routes/apartments.$id'

const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsRoute = ApartmentsRouteImport.update({
  id: '/apartments',
  path: '/apartments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsIdRoute = ApartmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApartmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apartments': typeof ApartmentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/my-orders': typeof MyOrdersRoute
  '/apartments/$id': typeof ApartmentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apartments': typeof ApartmentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/my-orders': typeof MyOrdersRoute
  '/apartments/$id': typeof ApartmentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apartments': typeof ApartmentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/my-orders': typeof MyOrdersRoute
  '/apartments/$id': typeof ApartmentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/apartments'
    | '/auth'
    | '/contact'
    | '/my-orders'
    | '/apartments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/apartments'
    | '/auth'
    | '/contact'
    | '/my-orders'
    | '/apartments/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/apartments'
    | '/auth'
    | '/contact'
    | '/my-orders'
    | '/apartments/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ApartmentsRoute: typeof ApartmentsRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  MyOrdersRoute: typeof MyOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments': {
      id: '/apartments'
      path: '/apartments'
      fullPath: '/apartments'
      preLoaderRoute: typeof ApartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments/$id': {
      id: '/apartments/$id'
      path: '/$id'
      fullPath: '/apartments/$id'
      preLoaderRoute: typeof ApartmentsIdRouteImport
      parentRoute: typeof ApartmentsRoute
    }
  }
}

interface ApartmentsRouteChildren {
  ApartmentsIdRoute: typeof ApartmentsIdRoute
}

const ApartmentsRouteChildren: ApartmentsRouteChildren = {
  ApartmentsIdRoute: ApartmentsIdRoute,
}

const ApartmentsRouteWithChildren = ApartmentsRoute._addFileChildren(
  ApartmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ApartmentsRoute: ApartmentsRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  MyOrdersRoute: MyOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
